export const LOGIN_ROUTE = "/login"
export const REGISTRATION_ROUTE = "/registration"
export const HOMEWORKS_ROUTE = "/homeworks"
export const ACCOUNT_ROUTE = "/profile"
export const USERS_ROUTE = "/users"
export const MAIN_ROUTE = "/main"
export const ADMIN_ROUTE = "/admin"
